site_name: CheckS
site_url: "https://github.com/Vini2/CheckS"
site_author: "Vijini Mallawaarachchi"
repo_url: "https://github.com/Vini2/CheckS"
repo_name: 'GitHub'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - shell
        - text
nav:
    - ABOUT:
      - Introduction: index.md
